// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search-suggestion-response.proto

package search.controllers.protobuf;

public final class SuggResp {
  private SuggResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SuggRespMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:search.SuggRespMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 count = 1;</code>
     */
    int getCount();

    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    java.util.List<search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion> 
        getSuggestionsList();
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion getSuggestions(int index);
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    int getSuggestionsCount();
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    java.util.List<? extends search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder> 
        getSuggestionsOrBuilderList();
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder getSuggestionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code search.SuggRespMsg}
   */
  public  static final class SuggRespMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:search.SuggRespMsg)
      SuggRespMsgOrBuilder {
    // Use SuggRespMsg.newBuilder() to construct.
    private SuggRespMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SuggRespMsg() {
      count_ = 0;
      suggestions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SuggRespMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              count_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                suggestions_ = new java.util.ArrayList<search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion>();
                mutable_bitField0_ |= 0x00000002;
              }
              suggestions_.add(
                  input.readMessage(search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          suggestions_ = java.util.Collections.unmodifiableList(suggestions_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              search.controllers.protobuf.SuggResp.SuggRespMsg.class, search.controllers.protobuf.SuggResp.SuggRespMsg.Builder.class);
    }

    public interface SuggestionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:search.SuggRespMsg.Suggestion)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string content = 1;</code>
       */
      java.lang.String getContent();
      /**
       * <code>optional string content = 1;</code>
       */
      com.google.protobuf.ByteString
          getContentBytes();
    }
    /**
     * Protobuf type {@code search.SuggRespMsg.Suggestion}
     */
    public  static final class Suggestion extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:search.SuggRespMsg.Suggestion)
        SuggestionOrBuilder {
      // Use Suggestion.newBuilder() to construct.
      private Suggestion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Suggestion() {
        content_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Suggestion(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                content_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_Suggestion_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_Suggestion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.class, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder.class);
      }

      public static final int CONTENT_FIELD_NUMBER = 1;
      private volatile java.lang.Object content_;
      /**
       * <code>optional string content = 1;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getContentBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getContentBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion)) {
          return super.equals(obj);
        }
        search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion other = (search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion) obj;

        boolean result = true;
        result = result && getContent()
            .equals(other.getContent());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code search.SuggRespMsg.Suggestion}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:search.SuggRespMsg.Suggestion)
          search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_Suggestion_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_Suggestion_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.class, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder.class);
        }

        // Construct using search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          content_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_Suggestion_descriptor;
        }

        public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion getDefaultInstanceForType() {
          return search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.getDefaultInstance();
        }

        public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion build() {
          search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion buildPartial() {
          search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion result = new search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion(this);
          result.content_ = content_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion) {
            return mergeFrom((search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion other) {
          if (other == search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.getDefaultInstance()) return this;
          if (!other.getContent().isEmpty()) {
            content_ = other.content_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object content_ = "";
        /**
         * <code>optional string content = 1;</code>
         */
        public java.lang.String getContent() {
          java.lang.Object ref = content_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            content_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string content = 1;</code>
         */
        public com.google.protobuf.ByteString
            getContentBytes() {
          java.lang.Object ref = content_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            content_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string content = 1;</code>
         */
        public Builder setContent(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          content_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string content = 1;</code>
         */
        public Builder clearContent() {
          
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }
        /**
         * <code>optional string content = 1;</code>
         */
        public Builder setContentBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          content_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:search.SuggRespMsg.Suggestion)
      }

      // @@protoc_insertion_point(class_scope:search.SuggRespMsg.Suggestion)
      private static final search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion();
      }

      public static search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Suggestion>
          PARSER = new com.google.protobuf.AbstractParser<Suggestion>() {
        public Suggestion parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Suggestion(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Suggestion> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Suggestion> getParserForType() {
        return PARSER;
      }

      public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int COUNT_FIELD_NUMBER = 1;
    private int count_;
    /**
     * <code>optional int32 count = 1;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int SUGGESTIONS_FIELD_NUMBER = 2;
    private java.util.List<search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion> suggestions_;
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    public java.util.List<search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion> getSuggestionsList() {
      return suggestions_;
    }
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    public java.util.List<? extends search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder> 
        getSuggestionsOrBuilderList() {
      return suggestions_;
    }
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    public int getSuggestionsCount() {
      return suggestions_.size();
    }
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion getSuggestions(int index) {
      return suggestions_.get(index);
    }
    /**
     * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
     */
    public search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder getSuggestionsOrBuilder(
        int index) {
      return suggestions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (count_ != 0) {
        output.writeInt32(1, count_);
      }
      for (int i = 0; i < suggestions_.size(); i++) {
        output.writeMessage(2, suggestions_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, count_);
      }
      for (int i = 0; i < suggestions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, suggestions_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof search.controllers.protobuf.SuggResp.SuggRespMsg)) {
        return super.equals(obj);
      }
      search.controllers.protobuf.SuggResp.SuggRespMsg other = (search.controllers.protobuf.SuggResp.SuggRespMsg) obj;

      boolean result = true;
      result = result && (getCount()
          == other.getCount());
      result = result && getSuggestionsList()
          .equals(other.getSuggestionsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      if (getSuggestionsCount() > 0) {
        hash = (37 * hash) + SUGGESTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getSuggestionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static search.controllers.protobuf.SuggResp.SuggRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(search.controllers.protobuf.SuggResp.SuggRespMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code search.SuggRespMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:search.SuggRespMsg)
        search.controllers.protobuf.SuggResp.SuggRespMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                search.controllers.protobuf.SuggResp.SuggRespMsg.class, search.controllers.protobuf.SuggResp.SuggRespMsg.Builder.class);
      }

      // Construct using search.controllers.protobuf.SuggResp.SuggRespMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSuggestionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        count_ = 0;

        if (suggestionsBuilder_ == null) {
          suggestions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          suggestionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return search.controllers.protobuf.SuggResp.internal_static_search_SuggRespMsg_descriptor;
      }

      public search.controllers.protobuf.SuggResp.SuggRespMsg getDefaultInstanceForType() {
        return search.controllers.protobuf.SuggResp.SuggRespMsg.getDefaultInstance();
      }

      public search.controllers.protobuf.SuggResp.SuggRespMsg build() {
        search.controllers.protobuf.SuggResp.SuggRespMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public search.controllers.protobuf.SuggResp.SuggRespMsg buildPartial() {
        search.controllers.protobuf.SuggResp.SuggRespMsg result = new search.controllers.protobuf.SuggResp.SuggRespMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.count_ = count_;
        if (suggestionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            suggestions_ = java.util.Collections.unmodifiableList(suggestions_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.suggestions_ = suggestions_;
        } else {
          result.suggestions_ = suggestionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof search.controllers.protobuf.SuggResp.SuggRespMsg) {
          return mergeFrom((search.controllers.protobuf.SuggResp.SuggRespMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(search.controllers.protobuf.SuggResp.SuggRespMsg other) {
        if (other == search.controllers.protobuf.SuggResp.SuggRespMsg.getDefaultInstance()) return this;
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (suggestionsBuilder_ == null) {
          if (!other.suggestions_.isEmpty()) {
            if (suggestions_.isEmpty()) {
              suggestions_ = other.suggestions_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSuggestionsIsMutable();
              suggestions_.addAll(other.suggestions_);
            }
            onChanged();
          }
        } else {
          if (!other.suggestions_.isEmpty()) {
            if (suggestionsBuilder_.isEmpty()) {
              suggestionsBuilder_.dispose();
              suggestionsBuilder_ = null;
              suggestions_ = other.suggestions_;
              bitField0_ = (bitField0_ & ~0x00000002);
              suggestionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSuggestionsFieldBuilder() : null;
            } else {
              suggestionsBuilder_.addAllMessages(other.suggestions_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        search.controllers.protobuf.SuggResp.SuggRespMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (search.controllers.protobuf.SuggResp.SuggRespMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int count_ ;
      /**
       * <code>optional int32 count = 1;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 1;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 1;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion> suggestions_ =
        java.util.Collections.emptyList();
      private void ensureSuggestionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          suggestions_ = new java.util.ArrayList<search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion>(suggestions_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder, search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder> suggestionsBuilder_;

      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public java.util.List<search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion> getSuggestionsList() {
        if (suggestionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(suggestions_);
        } else {
          return suggestionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public int getSuggestionsCount() {
        if (suggestionsBuilder_ == null) {
          return suggestions_.size();
        } else {
          return suggestionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion getSuggestions(int index) {
        if (suggestionsBuilder_ == null) {
          return suggestions_.get(index);
        } else {
          return suggestionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder setSuggestions(
          int index, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion value) {
        if (suggestionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuggestionsIsMutable();
          suggestions_.set(index, value);
          onChanged();
        } else {
          suggestionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder setSuggestions(
          int index, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder builderForValue) {
        if (suggestionsBuilder_ == null) {
          ensureSuggestionsIsMutable();
          suggestions_.set(index, builderForValue.build());
          onChanged();
        } else {
          suggestionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder addSuggestions(search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion value) {
        if (suggestionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuggestionsIsMutable();
          suggestions_.add(value);
          onChanged();
        } else {
          suggestionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder addSuggestions(
          int index, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion value) {
        if (suggestionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuggestionsIsMutable();
          suggestions_.add(index, value);
          onChanged();
        } else {
          suggestionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder addSuggestions(
          search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder builderForValue) {
        if (suggestionsBuilder_ == null) {
          ensureSuggestionsIsMutable();
          suggestions_.add(builderForValue.build());
          onChanged();
        } else {
          suggestionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder addSuggestions(
          int index, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder builderForValue) {
        if (suggestionsBuilder_ == null) {
          ensureSuggestionsIsMutable();
          suggestions_.add(index, builderForValue.build());
          onChanged();
        } else {
          suggestionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder addAllSuggestions(
          java.lang.Iterable<? extends search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion> values) {
        if (suggestionsBuilder_ == null) {
          ensureSuggestionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, suggestions_);
          onChanged();
        } else {
          suggestionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder clearSuggestions() {
        if (suggestionsBuilder_ == null) {
          suggestions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          suggestionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public Builder removeSuggestions(int index) {
        if (suggestionsBuilder_ == null) {
          ensureSuggestionsIsMutable();
          suggestions_.remove(index);
          onChanged();
        } else {
          suggestionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder getSuggestionsBuilder(
          int index) {
        return getSuggestionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder getSuggestionsOrBuilder(
          int index) {
        if (suggestionsBuilder_ == null) {
          return suggestions_.get(index);  } else {
          return suggestionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public java.util.List<? extends search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder> 
           getSuggestionsOrBuilderList() {
        if (suggestionsBuilder_ != null) {
          return suggestionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(suggestions_);
        }
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder addSuggestionsBuilder() {
        return getSuggestionsFieldBuilder().addBuilder(
            search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.getDefaultInstance());
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder addSuggestionsBuilder(
          int index) {
        return getSuggestionsFieldBuilder().addBuilder(
            index, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.getDefaultInstance());
      }
      /**
       * <code>repeated .search.SuggRespMsg.Suggestion suggestions = 2;</code>
       */
      public java.util.List<search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder> 
           getSuggestionsBuilderList() {
        return getSuggestionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder, search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder> 
          getSuggestionsFieldBuilder() {
        if (suggestionsBuilder_ == null) {
          suggestionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion, search.controllers.protobuf.SuggResp.SuggRespMsg.Suggestion.Builder, search.controllers.protobuf.SuggResp.SuggRespMsg.SuggestionOrBuilder>(
                  suggestions_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          suggestions_ = null;
        }
        return suggestionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:search.SuggRespMsg)
    }

    // @@protoc_insertion_point(class_scope:search.SuggRespMsg)
    private static final search.controllers.protobuf.SuggResp.SuggRespMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new search.controllers.protobuf.SuggResp.SuggRespMsg();
    }

    public static search.controllers.protobuf.SuggResp.SuggRespMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SuggRespMsg>
        PARSER = new com.google.protobuf.AbstractParser<SuggRespMsg>() {
      public SuggRespMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SuggRespMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SuggRespMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SuggRespMsg> getParserForType() {
      return PARSER;
    }

    public search.controllers.protobuf.SuggResp.SuggRespMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_search_SuggRespMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_search_SuggRespMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_search_SuggRespMsg_Suggestion_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_search_SuggRespMsg_Suggestion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n search-suggestion-response.proto\022\006sear" +
      "ch\"p\n\013SuggRespMsg\022\r\n\005count\030\001 \001(\005\0223\n\013sugg" +
      "estions\030\002 \003(\0132\036.search.SuggRespMsg.Sugge" +
      "stion\032\035\n\nSuggestion\022\017\n\007content\030\001 \001(\tB\'\n\033" +
      "search.controllers.protobufB\010SuggRespb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_search_SuggRespMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_search_SuggRespMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_search_SuggRespMsg_descriptor,
        new java.lang.String[] { "Count", "Suggestions", });
    internal_static_search_SuggRespMsg_Suggestion_descriptor =
      internal_static_search_SuggRespMsg_descriptor.getNestedTypes().get(0);
    internal_static_search_SuggRespMsg_Suggestion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_search_SuggRespMsg_Suggestion_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
