/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.search.SuggRespMsg');
goog.provide('proto.search.SuggRespMsg.Suggestion');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.search.SuggRespMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.search.SuggRespMsg.repeatedFields_, null);
};
goog.inherits(proto.search.SuggRespMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.search.SuggRespMsg.displayName = 'proto.search.SuggRespMsg';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.search.SuggRespMsg.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.search.SuggRespMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.search.SuggRespMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.search.SuggRespMsg} msg The msg instance to transform.
 * @return {!Object}
 */
proto.search.SuggRespMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    count: jspb.Message.getFieldWithDefault(msg, 1, 0),
    suggestionsList: jspb.Message.toObjectList(msg.getSuggestionsList(),
    proto.search.SuggRespMsg.Suggestion.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional int32 count = 1;
 * @return {number}
 */
proto.search.SuggRespMsg.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.search.SuggRespMsg.prototype.setCount = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated Suggestion suggestions = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.search.SuggRespMsg.Suggestion>}
 */
proto.search.SuggRespMsg.prototype.getSuggestionsList = function() {
  return /** @type{!Array.<!proto.search.SuggRespMsg.Suggestion>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.search.SuggRespMsg.Suggestion, 2));
};


/** @param {!Array.<!proto.search.SuggRespMsg.Suggestion>} value */
proto.search.SuggRespMsg.prototype.setSuggestionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.search.SuggRespMsg.Suggestion=} opt_value
 * @param {number=} opt_index
 * @return {!proto.search.SuggRespMsg.Suggestion}
 */
proto.search.SuggRespMsg.prototype.addSuggestions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.search.SuggRespMsg.Suggestion, opt_index);
};


proto.search.SuggRespMsg.prototype.clearSuggestionsList = function() {
  this.setSuggestionsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.search.SuggRespMsg.Suggestion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.search.SuggRespMsg.Suggestion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.search.SuggRespMsg.Suggestion.displayName = 'proto.search.SuggRespMsg.Suggestion';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.search.SuggRespMsg.Suggestion.prototype.toObject = function(opt_includeInstance) {
  return proto.search.SuggRespMsg.Suggestion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.search.SuggRespMsg.Suggestion} msg The msg instance to transform.
 * @return {!Object}
 */
proto.search.SuggRespMsg.Suggestion.toObject = function(includeInstance, msg) {
  var f, obj = {
    content: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional string content = 1;
 * @return {string}
 */
proto.search.SuggRespMsg.Suggestion.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.search.SuggRespMsg.Suggestion.prototype.setContent = function(value) {
  jspb.Message.setField(this, 1, value);
};


